name: freia
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - python=3.8.5
  - pytorch=1.8.0
  - torchvision=0.9.0
  - pip
  - pip:
    - git+https://github.com/VLL-HD/FrEIA.git@v0.2
    - h5py
    - jedi==0.17.2
    - matplotlib
    - pandas
    - seaborn
    - tqdm
    - gitpython
